//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPaySis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNTSEntities
    {
        public int ID_ACCOUNT { get; set; }
        public string NUM_ACCOUNT { get; set; }
    }
}
