//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPaySis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaysisEntities : DbContext
    {
        public PaysisEntities()
            : base("name=PaysisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNTSEntities> ACCOUNTSEntities { get; set; }
        public virtual DbSet<ROLESEntities> ROLESEntities { get; set; }
        public virtual DbSet<TRANSACTIONSEntities> TRANSACTIONSEntities { get; set; }
        public virtual DbSet<TYPESTRANSACTIONEntities> TYPESTRANSACTIONEntities { get; set; }
        public virtual DbSet<USERSEntities> USERSEntities { get; set; }
    }
}
